[feat] json parser #3
UNICT-DMI/UNICT-Elezioni pull request #4
Opened 2020-09-10 19:21 UTC by v0lp3

2020-09-10 19:32 UTC, Helias commented on jsonParser/dipartimenti.js
> +var fs = require('fs');
mai usare `var` in javascript/typescript.
Usa sempre e solo `let` o `const`, il primo per le variabili a cui reassigni un valore, il secondo per le costanti.

2020-09-10 19:32 UTC, Helias commented on jsonParser/dipartimenti.js
> +                info["votanti"] = element[1];
`switch case` is the way

2020-09-10 19:32 UTC, Helias commented on jsonParser/dipartimenti.js
> +        }
:+1:

2020-09-10 19:32 UTC, Helias commented on jsonParser/dipartimenti.js
> +                info["votanti"] = element[1];
Inoltre, potresti creare delle costanti ed evitare hard-coded text come "Schede Bianche" ed usare delle costanti o degli enum (purtroppo pero' gli enum ci sono solo in typescript e non in js se non erro).
```typescript
const SCHEDE_BIANCHE = "Schede Bianche"
```

2020-09-10 19:32 UTC, Helias commented on jsonParser/dipartimenti.js
> +                info["votanti"] = element[1];
Leggendo bene il codice, i primi tre casi li potresti "accorpare" facendo un'assegnazione del tipo
```typescript
info["schede"][element[0]] = element[1];
```

2020-09-10 19:33 UTC, Helias commented
Ho commentato un po' il codice, in realta' avrei 3mila cose da consigliarti, pero' non voglio annoiarti, non so se il tuo focus principale di ora sono le tecnologie web.
Ma.. dato che hai detto che forse imparerai React.js, beh impara che nel web e' meglio usare sempre e solo Typescript e non Javascript.
Typescript e' tipizzato e ti permette di gestire meglio la OOP e scrivere codice `pulito`.

Inoltre, ti aiuta a sistemare tutti gli hard-coded text di oggetti, stringhe ecc.

2020-09-10 20:12 UTC, v0lp3 commented
Apprezzo molto i tuoi suggerimenti/aiuto, non avere peli sulla lingua :sunglasses:

2020-09-10 21:31 UTC, Helias commented on jsonParser/organi_superiori.js
> +let info = {
questo e' una costante.
Quando crei un oggetto (quindi anche un array) il suo valore non e' altro che il puntatore di riferimento all'oggetto.
Quello che cambi sono i suoi elementi/attributi, ma il puntatore dell'oggetto e' quello fino a quando non effettui una riassegnazione della variabile info.

2020-09-10 21:36 UTC, Helias requested changes

2020-09-10 21:36 UTC, Helias commented on jsonParser/organi_superiori.js
> +    "liste": [], "eletti": []
i nomi degli attributi possono anche non essere dentro le doppie apici, per attributi con spazi puoi usare underscore o nomi brevi.

A me andrebbero anche bene cosi', ma qualche linter forse si lamenterebbe.

(Questo non vale quando scrivi file JSON).

2020-09-10 21:36 UTC, Helias commented on jsonParser/organi_superiori.js
> +                info["eletti"].push(eletto);
qui potresti anche scrivere `info.eletti`, i linter o gli interpreti run-time, potrebbero farei dei check se non usi `[""]` per modificare un attributo dell'oggetto

2020-09-10 21:36 UTC, Helias commented on jsonParser/organi_superiori.js
> +            if (element[2] == candidati.ELETTO) {
usa identical `===` anziche' equal `==`, in modo da controllare anche il tipo ed avere un check in piu' in questo controllo

2020-09-10 21:36 UTC, Helias commented on jsonParser/organi_superiori.js
> +    if (err) return console.log(err);
sconsiglio l'evitare di usare parentesi graffe per singole istruzioni

2020-09-11 09:07 UTC, Helias commented on jsonParser/dipartimenti.js
>      ELETTO: "ELETTO",
saro' un po' meticoloso, pero' lo standard javascript/typescript raccomanda di utilizzare le apici singole e non doppie :sweat_smile:

2020-09-11 17:01 UTC, Helias commented
Penso di averti stressato abbastanza, comunque per il futuro ti consiglio le seguenti cose:
- usa typescript e non javascript, non ha senso ormai usarlo
- usa un `linter`, aggiungi al tuo IDE qualche plugin come eslint (per js) o **tslint (per typescript)**, magari anche sonarlint per migliorare automaticamente tutto cio' (o quasi) quello che ti ho segnalato  in questa PR
- utilizza uno standard per scrivere le descrizioni dei commits esempio
Angular commits conventions: https://gist.github.com/brianclements/841ea7bffdb01346392c#type
Conventional Commits: https://www.conventionalcommits.org/en/v1.0.0/#summary (penso si rifacciano in realta' in parte a quelli di Angular)

2020-09-11 17:01 UTC, Helias approved these changes

2020-09-11 17:01 UTC, merged