refactor: extract components
UNICT-DMI/UNICT-Elezioni pull request #50
Opened 2020-09-24 21:27 UTC by drendog

The component `Results` seemed to be responsible for many things, so I have extracted some components to make the project more readable and maintainable as possible.
I hope I haven't messed up anything, and any advice is welcome.

2020-09-24 21:32 UTC, Helias commented on package.json
> +    "typescript": "^3.9.7"
ottimo

2020-09-24 21:32 UTC, Helias commented on src/app/results/DetailsTable.tsx
> +
questi spazi potremmo toglierli

2020-09-24 21:32 UTC, Helias commented on src/app/results/ListLogo/ListLogo.tsx
> +      .replace(props.listName, nameFixes[props.listName] ? nameFixes[props.listName] : props.listName)
bravo, hai tolto lo schifo xD

2020-09-24 21:32 UTC, Helias commented on src/app/results/ListLogo/nameFixes.ts
> +
mi piace come hai emarginato questo file

2020-09-24 21:32 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +
troppi spazi

2020-09-24 21:32 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +
il tuo vscode tratta l'indentazione a 4 spazi, usa quella a 2 spazi

2020-09-24 21:32 UTC, Helias commented on src/index.tsx
> -  </React.StrictMode>,
anch'io ho fatto lo stesso nell'altra PR

2020-09-24 21:34 UTC, Helias commented
Problema abbastanza serio: questa PR va in conflitto con la mia :sweat_smile:, nel senso che la parte delle schede contestate/nulle/bianche in realtà a me serve tenerla nel file Results, oppure, al massimo potresti cambiare i valori in input che prende questo componente che hai estratto in modo da ricevere in input i valori come schede contestate/nulle/bianche ecc. cosi' da non avere problemi.

Appena puoi dai un'occhiata alla mia PR e vedi che ho cambiato :P

2020-09-24 21:45 UTC, drendog commented
possiamo includere un linter (ESLint) con regole severe per evitare quegli errori di stile?

2020-09-24 21:49 UTC, Helias commented
assolutamente si, penso che con tslint gia' qualcosa la evitiamo, comunque dovremmo aggiungere tramite le github action per creare una pipeline che fa dei controlli al livello di linting

Ma per le cose di stile in realta', se hai installato eslint/tslint non penso che ti cambi qualcosa, devi modificare nelle impostazioni il plugin che ti indenta il codice automaticamente, oppure dire all'editor che un tab sono 2 spazi, o qualcosa del genere

2020-09-25 07:59 UTC, Helias requested changes

2020-09-25 07:59 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +					className="head-row cursorPointer"
`cursorPointer` non mi piace come nome xD 
nota che in CSS per le classi si usa il [kebab-case](https://it.wikipedia.org/wiki/Kebab_case)

2020-09-25 07:59 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +			<div className={show ? 'd-none' : 'd-block'}>
questo invece mi piace :P

2020-09-25 15:12 UTC, Helias commented
solve conflicts

2020-09-25 21:20 UTC, Helias commented on src/app/results/DetailsTable.tsx
> +	}
spaziature un po' esagerate

2020-09-25 21:20 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +	}
anche qui

2020-09-25 21:24 UTC, Helias approved these changes

2020-09-25 21:25 UTC, merged