Nuove features per il parser
UNICT-DMI/UNICT-Elezioni pull request #51
Opened 2020-09-25 11:14 UTC by Gigi-G

## Update

Adesso il parser può essere utilizzato anche per estrarre le informazioni del Nucleo di valutazione e del Comitato per lo sport universitario. Inoltre è stato notato che a volte alcuni seggi non vengono considerati nel conteggio finale (un bel mistero), nonostante questi figurino nel pdf. Per rimediare a ciò è stata aggiunta una parte interattiva, che non fa altro che chiedere all'utente quali seggi non bisogna considerare. Inoltre, questa parte interattiva non è sempre necessaria, perché sono state sfruttate delle informazioni presenti in alcuni pdf che permettono di bypassarla.

## Nuova documentazione

La nuova documentazione è già presente in /src/data/

2020-09-25 11:37 UTC, drendog approved these changes

2020-09-25 15:10 UTC, Helias requested changes

2020-09-25 15:10 UTC, Helias commented on jsonParser/create-json.py
> +    return(bool("CDL_B" not in filename.upper() and "INFERIORE" not in filename.upper() and "COORDIMAMENTO" not in filename.upper() and "COORDINAMENTO" not in filename.upper() and "DOTTORANDI" not in
potresti mettere tutte le stringhe da controllare in una lista e poi fare qualcosa come:
```python
matches = ["CDL_B", "INFERIORE", "COORDINAMENTO"....]
return bool(any(x not in filename.upper() for x in matches))
```
Più che altro perchè se un domani devi aggiungere o modificare la lista delle parole, non devi toccare la condizione e non scrivere tante volte `filename.upper()` ma puoi direttamente aggiungere o togliere una parola dalla lista.

Magari prova prima il codice nella console di python

fonte: https://stackoverflow.com/questions/3389574/check-if-multiple-strings-exist-in-another-string

2020-09-25 15:10 UTC, Helias commented on jsonParser/Organo.py
> +                k = k+1
`k+=1`

2020-09-25 15:10 UTC, Helias commented on jsonParser/Organo.py
> +                k += 1
```suggestion
            if len(listOfNot) > 0 and listOfNot[0]-1 == k: 
                    listSupport.append(listOfNot.pop(0))
            else:
                secondaryList["seggio_n_" + str(listOfSeats[k])] = int(v)
                k += 1
```

Praticamente ciò che c'è nell'else in basso lo ripeti esattamente identico dentro il secondo if, tanto vale che fai una sola condizione per `listSupport.append(listOfNot.pop(0))`

2020-09-25 15:10 UTC, Helias commented on jsonParser/Organo.py
> +                if self.is_integer(s):
se controlli che è un intero, perchè dopo lo converti ad int()?

2020-09-25 15:10 UTC, Helias commented on jsonParser/Organo.py
> +            while notSeggi != 0 and self.is_integer(notSeggi):
la prima volta che l'ho letto mi sembrava che avessi sbagliato e dovevi scrivere "not Seggi"

2020-09-25 15:10 UTC, Helias commented on jsonParser/Organo.py
> +                    notSeggi = int(input())
quindi, qui, stai chiedendo all'utente di inserire manualmente il seggio (?)
quello da escludere, il famoso numero maledetto 17?

2020-09-26 13:57 UTC, Gigi-G commented on jsonParser/Organo.py
> +                    notSeggi = int(input())
Si

2020-09-26 15:04 UTC, Gigi-G commented on jsonParser/Organo.py
> +        nomeOrgano = ""
Fatto!

2020-09-26 17:15 UTC, Helias approved these changes

2020-09-26 17:17 UTC, merged