feat(search): add search departments, lists, candidates
UNICT-DMI/UNICT-Elezioni pull request #69
Opened 2020-09-29 10:33 UTC by drendog

# Todo

- [ ] solve conflicts
- [ ] search by lists. Closes #66 
- [ ] search by candidates. Closes #56 
- [ ] improve graphics

Live version [here](https://drendog.github.io/UNICT-Elezioni/)
any advice is welcome.

2020-09-29 12:11 UTC, Helias requested changes

2020-09-29 12:11 UTC, Helias commented on src/app/App.tsx
> +  Redirect
I prefer to leave the comma when it is possible

2020-09-29 12:11 UTC, Helias commented on src/app/App.tsx
> -      <br />
we should avoid to use br, so, good job :+1:

2020-09-29 12:11 UTC, Helias commented on src/app/App.tsx
> +              years.map((y) => <Results anno={y} path={`dipartimenti/${d}`} details={false} key={`${d}${y}`} showDetailsList />)
`showDetailsList` is not used I think, so you could even remove it and put in the component props it as a "optional" attribute using `?` at the end of the attribute in the Prop interface

2020-09-29 12:11 UTC, Helias commented on src/app/results/DetailList/DetailsList.tsx
> +  function generateVotesRow (): JSX.Element {
why that space? :imp:

2020-09-29 12:11 UTC, Helias commented on src/app/results/DetailList/DetailsList.tsx
> +};
I don't think that this last semi-colon is needed

2020-09-29 12:11 UTC, Helias commented on src/app/results/ListLogo/ListLogo.tsx
> +};
same

2020-09-29 12:11 UTC, Helias commented on src/app/search/SearchEngine.ts
> +  search (str: string): string[] {
`function()` not `function ()` :(

2020-09-29 12:11 UTC, Helias commented on src/index.tsx
> +  document.getElementById('root')
I would leave the comma

2020-09-29 12:12 UTC, Helias commented on src/app/search/SearchForm.tsx
> +  </div>);
this feature is fantastic

2020-09-29 12:22 UTC, Helias commented on src/app/search/SearchForm.tsx
> +    return results;
```suggestion
    return suggestions.map((s) => {
        <a href={`#/dipartimento/${s}`}>
          <ListGroup.Item action variant="light">
            {s.replaceAll('_', ' ')}
          </ListGroup.Item>
        </a>
    });
```
```

2020-09-29 17:58 UTC, drendog commented
so, about the spaces after the function name and the comma style, this is a rule defined by [standardjs](https://standardjs.com/rules.html) `space-before-function-paren` and `comma-style`, eslint will warn us for the missing space, but if you don't like it, I can disable this rule at any time. About the semi-colon, I added the rule (semi) for forcing its consistent use, and I can disable this too.

2020-09-29 18:00 UTC, Helias commented
@drendog I think that probably we need to use tslint, anyways, personally I hate those spaces 😅

2020-09-30 08:12 UTC, drendog commented
Added the search by list, it is not ended yet, but any advice is welcome.
[TSLint](https://palantir.github.io/tslint/) has been **deprecated** as of 2019, and their devs advice us to migrate to ESLint. It is customizable and seems to work fine, if you don't like some style, you can add some rules on '.eslintrc.json'. Now I added the rule for remove those spaces, if the comma style looks bad too, I can remove it if you want.

2020-09-30 08:13 UTC, Helias commented
@drendog 😨, ok 😔

2020-10-02 08:59 UTC, Helias requested changes

2020-10-02 08:59 UTC, Helias commented on src/app/results/DetailList/Seggi.ts
> +  getSeggi(): string[] {
```suggestion
  get seggi(): string[] {
```

2020-10-02 08:59 UTC, Helias commented on src/app/results/Results.tsx
> +        }
very very nice!

2020-10-02 08:59 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +          {Object.keys(results).map((l: string) => l !== 'undefined' &&
I think that this can be improved

2020-10-02 08:59 UTC, Helias commented on src/app/results/ResultsTable.tsx
> +  function toggleBody(e: any): void {
:relieved:

2020-10-02 08:59 UTC, Helias commented on src/app/search/SearchEngine.ts
> +  }
I don't really like the logic here, even because when you do `isPresent = true;` in the next iteration you could not find the namePart and set it false back.
You should add a `break;` after `isPresent = true;`

But you can improve this in a really better way.
- remove the variable isPresent
- if you find it `return true` directly
- otherwise `return false`

2020-10-02 08:59 UTC, Helias commented on src/app/search/SearchEngine.ts
> +  private constructor() {
:thinking:

2020-10-02 08:59 UTC, Helias commented on src/app/search/SearchEngine.ts
> +  private constructor() {
ah ma e' un singleton :grin:

2020-10-02 08:59 UTC, Helias commented on src/app/search/SearchForm.tsx
> +    ) as any;
sooner or later we need to add the types for everything

2020-10-02 08:59 UTC, Helias commented on src/app/search/SearchForm.tsx
> +    <ListGroup className={formValue.length > 0 ? 'suggestions-list' : 'd-none'}>
you can even omit the `> 0`

2020-10-02 08:59 UTC, Helias commented on src/data/entities.ts
> +};
may an `enum` can be a better choice (?)

2020-10-02 08:59 UTC, Helias commented on src/data/entities.ts
> +export default entities;
you could directly `export entities` instead of using `export default entitites;`

2020-10-02 09:39 UTC, Helias commented on src/app/search/SearchEngine.ts
> +  }
nevermind, that's ok

2020-10-02 23:06 UTC, drendog commented on src/app/App.tsx
> +              years.map((y) => <Results anno={y} path={`dipartimenti/${d}`} details={false} key={`${d}${y}`} showDetailsList />)
I use `showDetailsList` for popover that show the seats table, because if I use this popover on the Senate, the table will be very long, and it can get out of the page limits.

2020-10-02 23:22 UTC, drendog commented on src/data/entities.ts
> +};
maybe no, because i'm using `IEntitiesPath` interface

2020-10-03 10:45 UTC, Helias commented on src/app/App.tsx
> +            <Contacts/>
:+1:

2020-10-03 11:51 UTC, drendog commented
approved?

2020-10-03 11:53 UTC, Helias approved these changes

2020-10-03 11:53 UTC, Helias commented
yes

2020-10-03 11:56 UTC, merged