feat: Parser
UNICT-DMI/UNICT-Elezioni pull request #71
Opened 2020-10-02 14:32 UTC by Gigi-G

## Nuove caratteristiche
Adesso è possibile estrarre informazioni che riguardano:
- ERSU #33 
- CdL > 500 e CdL < 500 #54 
- Coordinamento di medicina #55 

## Nuova documentazione
La nuova documentazione è reperibile in **/src/data/**

2020-10-02 18:24 UTC, Helias requested changes

2020-10-02 18:24 UTC, Helias commented on jsonParser/CdlInf.py
> +        return result
```suggestion
        if not self.word_not_in_control("NO QUORUM", text):
            text[self.i] = text[self.i].replace("NO QUORUM", " ").strip()
            return False

        return True
```

2020-10-02 18:24 UTC, Helias commented on jsonParser/CdlInf.py
> +                if not self.word_not_in_control("EX AEQUO", text):
`elif`....?

2020-10-02 18:24 UTC, Helias commented on jsonParser/CdlInf.py
> +                    })
If you want you could write
```suggestion
                e = {
                        "nome_candidato": nome_candidato.strip(),
                        "voti": int(voti_candidato)
                };
                if eletto:
                    eletti.append(e)
                else:
                    non_eletti.append(e)
```

2020-10-02 18:24 UTC, Helias commented on jsonParser/Medicina.py
> +                })
same here

2020-10-02 18:24 UTC, Helias commented on jsonParser/Medicina.py
> +        self.__get_extract_info(text, tmp, totale_voti, list_of_seats)
```suggestion
        tmp = [1]
        schede_bianche = [1]
        schede_nulle = [1]
        schede_contestate = [1]
        totale_voti = [1]
        self.__get_candidati(text, list_of_seats, eletti, non_eletti)
        self.__get_extract_info(text, tmp, schede_bianche, list_of_seats)
        self.__get_extract_info(text, tmp, schede_nulle, list_of_seats)
        self.__get_extract_info(text, tmp, schede_contestate, list_of_seats)
        self.__get_extract_info(text, tmp, totale_voti, list_of_seats)
```

2020-10-02 18:24 UTC, Helias commented on jsonParser/Organo.py
> +                    find_d = self.__automatic_control1(j, text2)
```python
elif not find_d:
....
```
instead of else: -> if:

2020-10-02 18:24 UTC, Helias commented on jsonParser/README.md
> +  `[0|1|other]` indicates the type of data to parse.
`[0|1|2|other]`

2020-10-02 18:24 UTC, Helias commented on jsonParser/README.md
> +  `[0|1|other]` indicates the type of data to parse.
`[0|1|2|other]`

2020-10-03 14:04 UTC, Gigi-G commented on jsonParser/CdlInf.py
> +                if not self.word_not_in_control("EX AEQUO", text):
else if in python

2020-10-03 14:46 UTC, merged